const config = {
  STREAM_PLAYBACK_URL: process.env.REACT_APP_STREAM_PLAYBACK_URL,
  WS_REKOGNITION_URL: process.env.REACT_APP_WS_REKOGNITION_URL,
  DISPLAY_CONFIDENCE_THRESHOLD: process.env.REACT_APP_DISPLAY_CONFIDENCE_THRESHOLD,
  MAX_CONCURRENT_BOXES: process.env.REACT_APP_MAX_CONCURRENT_BOXES
};

export default config;
